version: '3.4'

services:
  innoloftwebapi:
    image: ${DOCKER_REGISTRY-}innoloftwebapi
    build:
      context: .
      dockerfile: InnoloftWebAPI/Dockerfile

  s_mysql:
    container_name: c_mysql
    image: mysql:5.7
